# [AUTO-GENERATED BY SYSTEM] – Modifications should be tracked and reviewed
\20250523_160150 = Get-Date -Format "yyyyMMdd_HHmmss"
\dist\mod_001.exe = "dist/sample_model.exe"
\deploy = "deploy"
if (-not (Test-Path \deploy)) { New-Item -ItemType Directory -Path \deploy | Out-Null }
if (Test-Path \dist\mod_001.exe) {
    Copy-Item \dist\mod_001.exe "\deploy/sample_model.exe" -Force
    Write-Host "Deployment successful."
} else {
    Write-Host "Deployment failed: \dist\mod_001.exe not found."
}
